### PR TITLE
Update Readme to point to hydra-editor not hydra-editor-1

### PR DESCRIPTION
**Pull request by mcscope**
Document sharing keyboard command re: issue #42

### CODE REVIEW

**Comment by mcscope** [comment]
@ojack How would you feel about having the twitter share option appear for all sketches, whether they're original or from a share themselves?

**Comment by ojack** [comment]
It does appear for all? Or did I miss understand? It only works from this link: https://hydra-editor.glitch.me

**Comment by mcscope** [comment]
@ojack You are correct! I'll update the url in the readme

**Comment by mcscope** [comment]
@ojack  I updated this PR

**Pull request merged**
