### PR TITLE
add a hot key to format editor code with Prettier

### PR DESCRIPTION
**Pull request by frodosamoa**
code formatting shouldn't be the worry of someone who is live coding, the code formatting should actually help them live code!

this PR adds the hot key `control + shift + f` to format the code in the editor with [Prettier](https://prettier.io/). 

here is a .gif example of how this would work:
Kapture 2020-05-07 at 0 46 38

happy to talk about some sensible defaults (like `printWidth`) as well at finding the right hot key ☺️ 

hope this helps people code live!

### CODE REVIEW

**Comment by ojack** [comment]
ooo this is great!

**Comment by zachkrall** [comment]
😆 ahaha i like my messy style

this is a great idea tho! 👍

**Comment by ojack** [comment]
Hahah yeah part of me really cringes at the idea that some code is "prettier" than others (but this is practical)

**Comment by zachkrall** [comment]
oh yeah I agree! This is a super helpful addition. I can see it being useful for debugging like a missing closing paren or something.

**Comment by frodosamoa** [comment]
the name `prettier` can definitely unintentionally lead some users to think there is a bias in how "pretty" code 🙈 we can always add some sensible defaults that people agree on! semi colons, line width, etc.

**Pull request merged**
