### PR TITLE
Point Mutation Glitcher

### PR DESCRIPTION
**Pull request by jamiefaye**
I added a 'dice' button to make it easier to trigger the PMG. Holding shift down when pressing the dice button undos one level each time. All the Shift-control characters still work as well.

I am making this PR to get a discussion started. I expect to change things as requested.

### CODE REVIEW

**Comment by ojack** [comment]
Hi @jamiefaye, I am just seeing this now for some reason, sorry about the delay!!! Am going to look at it tomorrow but in general I really like the idea.

**Comment by jamiefaye** [comment]
No problem. I have a number of improvements in mind, so we don't need to
merge this in right away.

– Jamie

**Comment by ojack** [comment]
Hi!

I just merged to master :) I had done a small refactor of separating the evaluation code from the editor, and separating key commands from the editor as well, so just made a few changes to reflect that. This is so fun and I am really excited about it.

A few thoughts:
-- The undo stack seems really useful in general for people to undo changes they have made! 
-- It would be fun to briefly highlight the section of the code that has changed. I finally added that for executing code, so it should be possible.. https://github.com/ojack/hydra/blob/b830d4334309c18bcbcef0f74369914b86d97293/hydra-server/app/src/editor.js#L96

-- One thing that I think can be confusing and complicated in general is that the text in the editor doesn't represent the actual state of the system. i.e.more than one piece of code can refer to the same buffer. I tried out a different type of editing in pixeljam: http://pixeljam.glitch.me/ that maybe is a more straightforward representation of what is actually happening, and makes "undoing" make more sense, but has other tradeoffs. In my own version of hydra, I have tried some things like recording my changes to the code, and then replaying them on a timeline while adding new changes (also having a scrubbable timeline of past changes). It is really fun but gets kind of confusing in terms of what is happening in the editor vs the state of the system. These kinds of ideas might be fun to play around with in dev versions before adding to the public editor.
-- I am not very familiar with Abstract Syntax Trees and am excited to dig into that part more :)
-- Would be interesting to adjust ranges of glitching, also be able to select which field (maybe just the field closest to the cursor)

**Comment by ojack** [comment]
In terms of continuous updates from one change to the other, I think it wouldn't be *too* complicated...since the mutation glitcher is only changing numbers, and hydra can accept functions as values. Here is a function to interpolate between two numbers:
`
interpolateSpeed = 10 // seconds

interpolate = (curr, next) => () => {
  var t = Math.min(time - timeOfLastCodeChange, interpolateSpeed)/interpolateSpeed
  return   next*t + curr*(1-t)
}
`

That can be used in hydra like
`
timeOfLastCodeChange = time
osc(interpolate(0, 100), 0, 0.7).out(o0)
`

I think it would be possible for the mutation glitcher behind the scenes to call the interpolate function on each updated value, wheras the user only sees the updated value.

**Pull request merged**
